version: 0.1

phases:
  pre_build:
    commands:
      - chmod +x ./gradlew
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean lintKotlin test jacocoTestReport
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/reports/**/*
